### ISSUE TITLE
Merge with "eslint-plugin-ember" 

### ISSUE THREAD

**Issue by Turbo87** [onechiporenko/eslint-plugin-ember-cleanup#1]
It seems like wasted effort to have two separate ESLint plugins for Ember.js. It would be awesome if this project would merge with [eslint-plugin-ember](https://github.com/zipscene/eslint-plugin-ember) and offer all of the rules in the "eslint-plugin-ember" package.

**Comment by BrianSipple** [comment]
ping. 

Also, 👍

**Comment by scottkidder** [comment]
The link above is to an old repo. Here is the correct link to [eslint-plugin-ember](https://github.com/ember-cli/eslint-plugin-ember)
